// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRe0YkXrrRUjRKhZtbO_pUdMmm4hoD7z4',
    appId: '1:947473130835:web:5774ea7e110c21e865eda6',
    messagingSenderId: '947473130835',
    projectId: 'djal-auto-be4ed',
    authDomain: 'djal-auto-be4ed.firebaseapp.com',
    storageBucket: 'djal-auto-be4ed.appspot.com',
    measurementId: 'G-BVCR8RMWSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZNM7kXzAMlRktOJTXLcjobS_b-jpwFpI',
    appId: '1:947473130835:android:089c6c93888c906565eda6',
    messagingSenderId: '947473130835',
    projectId: 'djal-auto-be4ed',
    storageBucket: 'djal-auto-be4ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr9P8BWVTFF65e9LFKnRRuZIZH5l0TMxQ',
    appId: '1:947473130835:ios:c0897ea9a82bf90c65eda6',
    messagingSenderId: '947473130835',
    projectId: 'djal-auto-be4ed',
    storageBucket: 'djal-auto-be4ed.appspot.com',
    androidClientId: '947473130835-rkq7hqr3gpr7apmf6o246h6894u79qha.apps.googleusercontent.com',
    iosClientId: '947473130835-5s525hlgi8v0bvrcm7fei6qfq7dqm07u.apps.googleusercontent.com',
    iosBundleId: 'com.ho1yspirt.djalAuto',
  );
}
